"""add_missing_factory_columns

Revision ID: a13b0ee61914
Revises: 295f2319d69d
Create Date: 2025-12-04 13:50:26.868165+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13b0ee61914'
down_revision: Union[str, None] = '295f2319d69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('contract_start_date', sa.Date(), nullable=True))
    op.add_column('factories', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_factories_contract_end_date'), 'factories', ['contract_end_date'], unique=False)
    op.create_index(op.f('ix_factories_contract_start_date'), 'factories', ['contract_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_contract_start_date'), table_name='factories')
    op.drop_index(op.f('ix_factories_contract_end_date'), table_name='factories')
    op.drop_column('factories', 'contract_end_date')
    op.drop_column('factories', 'contract_start_date')
    # ### end Alembic commands ###
