"""Add missing supervisor_position column to factory_lines

Revision ID: 295f2319d69d
Revises: 005_factory_contact_positions
Create Date: 2025-12-03 15:39:16.164940+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '295f2319d69d'
down_revision: Union[str, None] = '005_factory_contact_positions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_companies_base_madre_id', table_name='companies')
    op.drop_constraint('uq_base_madre_company_id', 'companies', type_='unique')
    op.create_index(op.f('ix_companies_base_madre_company_id'), 'companies', ['base_madre_company_id'], unique=True)
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.alter_column('dispatch_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('dispatch_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_dispatch_assignments_id'), 'dispatch_assignments', ['id'], unique=False)
    op.alter_column('employees', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'transportation_allowance',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('employees', 'has_employment_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'has_health_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'has_pension_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'has_workers_comp',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'yukyu_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'yukyu_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'yukyu_remaining',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'is_corporate_housing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'housing_subsidy',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('employees', 'forklift_license',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('employees_employee_number_key', 'employees', type_='unique')
    op.drop_index('ix_employees_company_name', table_name='employees')
    op.drop_index('ix_employees_status_visa', table_name='employees', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index('ix_employees_employee_number', table_name='employees')
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_index('ix_employees_company', 'employees', ['company_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index('ix_employees_name_kana', 'employees', ['full_name_kana'], unique=False)
    op.create_index('ix_employees_visa_expiry', 'employees', ['visa_expiry_date'], unique=False)
    op.drop_constraint('employees_factory_id_fkey', 'employees', type_='foreignkey')
    op.drop_constraint('employees_factory_line_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'factories', ['factory_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'factory_lines', ['factory_line_id'], ['id'])
    op.alter_column('factories', 'client_responsible_position',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Client responsible person position (e.g., 課長, 部長, 責任者)',
               existing_nullable=True)
    op.alter_column('factories', 'client_complaint_position',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Client complaint contact position (e.g., 担当者, 課長, 部長)',
               existing_nullable=True)
    op.alter_column('factories', 'break_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('factories', 'contract_cycle_type',
               existing_type=postgresql.ENUM('monthly', 'annual', name='contract_cycle_type'),
               server_default=None,
               existing_comment='月次契約 or 年間契約',
               existing_nullable=False)
    op.alter_column('factories', 'cycle_day_type',
               existing_type=postgresql.ENUM('fixed', 'month_end', name='contract_cycle_day_type'),
               server_default=None,
               existing_comment='固定日 or 月末',
               existing_nullable=False)
    op.alter_column('factories', 'fiscal_year_end_month',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='決算月 (1-12)',
               existing_nullable=False)
    op.alter_column('factories', 'fiscal_year_end_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='決算日 (1-31)',
               existing_nullable=False)
    op.alter_column('factories', 'contract_renewal_days_before',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='自動更新通知日数',
               existing_nullable=False)
    op.alter_column('factories', 'time_unit_minutes',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('factories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('factories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('factories_factory_id_key', 'factories', type_='unique')
    op.drop_index('ix_factories_factory_id', table_name='factories')
    op.create_index(op.f('ix_factories_factory_id'), 'factories', ['factory_id'], unique=True)
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    op.drop_column('factories', 'supervisor_position')
    op.add_column('factory_lines', sa.Column('supervisor_position', sa.String(length=100), nullable=True))
    op.alter_column('factory_lines', 'responsibility_level',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('factory_lines', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('factory_lines', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('factory_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_factory_lines_active', table_name='factory_lines', postgresql_where='(is_active = true)')
    op.drop_index('ix_factory_lines_factory_id', table_name='factory_lines')
    op.create_index('ix_factory_lines_factory', 'factory_lines', ['factory_id'], unique=False)
    op.create_index(op.f('ix_factory_lines_id'), 'factory_lines', ['id'], unique=False)
    op.alter_column('jigyosho', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jigyosho', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('jigyosho', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_jigyosho_base_madre_id', table_name='jigyosho')
    op.drop_constraint('uq_base_madre_jigyosho_id', 'jigyosho', type_='unique')
    op.create_index(op.f('ix_jigyosho_base_madre_jigyosho_id'), 'jigyosho', ['base_madre_jigyosho_id'], unique=True)
    op.create_index(op.f('ix_jigyosho_jigyosho_id'), 'jigyosho', ['jigyosho_id'], unique=False)
    op.alter_column('kobetsu_employees', 'is_indefinite_employment',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_kobetsu_employees_dates', table_name='kobetsu_employees')
    op.create_index(op.f('ix_kobetsu_employees_id'), 'kobetsu_employees', ['id'], unique=False)
    op.create_index(op.f('ix_kobetsu_employees_kobetsu_keiyakusho_id'), 'kobetsu_employees', ['kobetsu_keiyakusho_id'], unique=False)
    op.alter_column('kobetsu_keiyakusho', 'company_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to companies table',
               existing_nullable=True)
    op.alter_column('kobetsu_keiyakusho', 'plant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to plants table',
               existing_nullable=True)
    op.alter_column('kobetsu_keiyakusho', 'previous_contract_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID of the previous contract (for renewals)',
               existing_nullable=True)
    op.alter_column('kobetsu_keiyakusho', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_kobetsu_company_id', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_company_plant_status', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_created_at', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_factory_status', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_plant_id', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_previous_contract', table_name='kobetsu_keiyakusho')
    op.drop_index('ix_kobetsu_status_dates', table_name='kobetsu_keiyakusho')
    op.drop_constraint('kobetsu_keiyakusho_contract_number_key', 'kobetsu_keiyakusho', type_='unique')
    op.drop_constraint('uq_kobetsu_contract_number', 'kobetsu_keiyakusho', type_='unique')
    op.create_index(op.f('ix_kobetsu_keiyakusho_company_id'), 'kobetsu_keiyakusho', ['company_id'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_contract_number'), 'kobetsu_keiyakusho', ['contract_number'], unique=True)
    op.create_index(op.f('ix_kobetsu_keiyakusho_dispatch_end_date'), 'kobetsu_keiyakusho', ['dispatch_end_date'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_dispatch_start_date'), 'kobetsu_keiyakusho', ['dispatch_start_date'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_factory_id'), 'kobetsu_keiyakusho', ['factory_id'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_id'), 'kobetsu_keiyakusho', ['id'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_plant_id'), 'kobetsu_keiyakusho', ['plant_id'], unique=False)
    op.create_index(op.f('ix_kobetsu_keiyakusho_previous_contract_id'), 'kobetsu_keiyakusho', ['previous_contract_id'], unique=False)
    op.alter_column('plants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_plants_base_madre_id', table_name='plants')
    op.drop_constraint('uq_base_madre_plant_id', 'plants', type_='unique')
    op.create_index(op.f('ix_plants_base_madre_plant_id'), 'plants', ['base_madre_plant_id'], unique=True)
    op.create_index(op.f('ix_plants_plant_id'), 'plants', ['plant_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_plants_plant_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_base_madre_plant_id'), table_name='plants')
    op.create_unique_constraint('uq_base_madre_plant_id', 'plants', ['base_madre_plant_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_plants_base_madre_id', 'plants', ['base_madre_plant_id'], unique=False)
    op.alter_column('plants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('plants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('plants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_kobetsu_keiyakusho_previous_contract_id'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_plant_id'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_id'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_factory_id'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_dispatch_start_date'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_dispatch_end_date'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_contract_number'), table_name='kobetsu_keiyakusho')
    op.drop_index(op.f('ix_kobetsu_keiyakusho_company_id'), table_name='kobetsu_keiyakusho')
    op.create_unique_constraint('uq_kobetsu_contract_number', 'kobetsu_keiyakusho', ['contract_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('kobetsu_keiyakusho_contract_number_key', 'kobetsu_keiyakusho', ['contract_number'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_kobetsu_status_dates', 'kobetsu_keiyakusho', ['status', 'dispatch_start_date', 'dispatch_end_date'], unique=False)
    op.create_index('ix_kobetsu_previous_contract', 'kobetsu_keiyakusho', ['previous_contract_id'], unique=False)
    op.create_index('ix_kobetsu_plant_id', 'kobetsu_keiyakusho', ['plant_id'], unique=False)
    op.create_index('ix_kobetsu_factory_status', 'kobetsu_keiyakusho', ['factory_id', 'status'], unique=False)
    op.create_index('ix_kobetsu_created_at', 'kobetsu_keiyakusho', ['created_at'], unique=False)
    op.create_index('ix_kobetsu_company_plant_status', 'kobetsu_keiyakusho', ['company_id', 'plant_id', 'status'], unique=False)
    op.create_index('ix_kobetsu_company_id', 'kobetsu_keiyakusho', ['company_id'], unique=False)
    op.alter_column('kobetsu_keiyakusho', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('kobetsu_keiyakusho', 'previous_contract_id',
               existing_type=sa.INTEGER(),
               comment='ID of the previous contract (for renewals)',
               existing_nullable=True)
    op.alter_column('kobetsu_keiyakusho', 'plant_id',
               existing_type=sa.INTEGER(),
               comment='Reference to plants table',
               existing_nullable=True)
    op.alter_column('kobetsu_keiyakusho', 'company_id',
               existing_type=sa.INTEGER(),
               comment='Reference to companies table',
               existing_nullable=True)
    op.drop_index(op.f('ix_kobetsu_employees_kobetsu_keiyakusho_id'), table_name='kobetsu_employees')
    op.drop_index(op.f('ix_kobetsu_employees_id'), table_name='kobetsu_employees')
    op.create_index('ix_kobetsu_employees_dates', 'kobetsu_employees', ['kobetsu_keiyakusho_id', 'individual_start_date', 'individual_end_date'], unique=False)
    op.alter_column('kobetsu_employees', 'is_indefinite_employment',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_index(op.f('ix_jigyosho_jigyosho_id'), table_name='jigyosho')
    op.drop_index(op.f('ix_jigyosho_base_madre_jigyosho_id'), table_name='jigyosho')
    op.create_unique_constraint('uq_base_madre_jigyosho_id', 'jigyosho', ['base_madre_jigyosho_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_jigyosho_base_madre_id', 'jigyosho', ['base_madre_jigyosho_id'], unique=False)
    op.alter_column('jigyosho', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('jigyosho', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('jigyosho', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_factory_lines_id'), table_name='factory_lines')
    op.drop_index('ix_factory_lines_factory', table_name='factory_lines')
    op.create_index('ix_factory_lines_factory_id', 'factory_lines', ['factory_id'], unique=False)
    op.create_index('ix_factory_lines_active', 'factory_lines', ['factory_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('factory_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_lines', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('factory_lines', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('factory_lines', 'responsibility_level',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'通常業務'::character varying"),
               nullable=False)
    op.drop_column('factory_lines', 'supervisor_position')
    op.add_column('factories', sa.Column('supervisor_position', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Supervisor position (e.g., 課長, 部長, リーダー)'))
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_index(op.f('ix_factories_factory_id'), table_name='factories')
    op.create_index('ix_factories_factory_id', 'factories', ['factory_id'], unique=False)
    op.create_unique_constraint('factories_factory_id_key', 'factories', ['factory_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('factories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('factories', 'time_unit_minutes',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               server_default=sa.text("'15'::numeric"),
               existing_nullable=True)
    op.alter_column('factories', 'contract_renewal_days_before',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_comment='自動更新通知日数',
               existing_nullable=False)
    op.alter_column('factories', 'fiscal_year_end_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('31'),
               existing_comment='決算日 (1-31)',
               existing_nullable=False)
    op.alter_column('factories', 'fiscal_year_end_month',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_comment='決算月 (1-12)',
               existing_nullable=False)
    op.alter_column('factories', 'cycle_day_type',
               existing_type=postgresql.ENUM('fixed', 'month_end', name='contract_cycle_day_type'),
               server_default=sa.text("'fixed'::contract_cycle_day_type"),
               existing_comment='固定日 or 月末',
               existing_nullable=False)
    op.alter_column('factories', 'contract_cycle_type',
               existing_type=postgresql.ENUM('monthly', 'annual', name='contract_cycle_type'),
               server_default=sa.text("'annual'::contract_cycle_type"),
               existing_comment='月次契約 or 年間契約',
               existing_nullable=False)
    op.alter_column('factories', 'break_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               nullable=False)
    op.alter_column('factories', 'client_complaint_position',
               existing_type=sa.VARCHAR(length=100),
               comment='Client complaint contact position (e.g., 担当者, 課長, 部長)',
               existing_nullable=True)
    op.alter_column('factories', 'client_responsible_position',
               existing_type=sa.VARCHAR(length=100),
               comment='Client responsible person position (e.g., 課長, 部長, 責任者)',
               existing_nullable=True)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_factory_line_id_fkey', 'employees', 'factory_lines', ['factory_line_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('employees_factory_id_fkey', 'employees', 'factories', ['factory_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_employees_visa_expiry', table_name='employees')
    op.drop_index('ix_employees_name_kana', table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index('ix_employees_company', table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.create_index('ix_employees_employee_number', 'employees', ['employee_number'], unique=False)
    op.create_index('ix_employees_status_visa', 'employees', ['status', 'visa_expiry_date'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_index('ix_employees_company_name', 'employees', ['company_name'], unique=False)
    op.create_unique_constraint('employees_employee_number_key', 'employees', ['employee_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'forklift_license',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('employees', 'housing_subsidy',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('employees', 'is_corporate_housing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('employees', 'yukyu_remaining',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('employees', 'yukyu_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('employees', 'yukyu_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('employees', 'has_workers_comp',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('employees', 'has_pension_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('employees', 'has_health_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('employees', 'has_employment_insurance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('employees', 'transportation_allowance',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               nullable=False)
    op.alter_column('employees', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ベトナム'::character varying"),
               nullable=False)
    op.drop_index(op.f('ix_dispatch_assignments_id'), table_name='dispatch_assignments')
    op.alter_column('dispatch_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispatch_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_base_madre_company_id'), table_name='companies')
    op.create_unique_constraint('uq_base_madre_company_id', 'companies', ['base_madre_company_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_companies_base_madre_id', 'companies', ['base_madre_company_id'], unique=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###
